# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "clone"
client_id = "1ac1e80492380848919cffbfe7b9c4de"
application_url = "https://nicaragua-roots-burn-drive.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://nicaragua-roots-burn-drive.trycloudflare.com/auth/callback",
  "https://nicaragua-roots-burn-drive.trycloudflare.com/auth/shopify/callback",
  "https://nicaragua-roots-burn-drive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appmixo-disha.myshopify.com"
